// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ru0xipTjfvZZUw9WPu7hRhCviCkRd-k',
    appId: '1:159145555084:web:e17974b36d3c1ece76f7a9',
    messagingSenderId: '159145555084',
    projectId: 'noteapp-38cb3',
    authDomain: 'noteapp-38cb3.firebaseapp.com',
    storageBucket: 'noteapp-38cb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBG18z5rugzvQBf51RatIobI1cG9VRVw',
    appId: '1:159145555084:android:617ebc47808d2cd576f7a9',
    messagingSenderId: '159145555084',
    projectId: 'noteapp-38cb3',
    storageBucket: 'noteapp-38cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-I7BI1sThCGlofSSrmMlidyah8PVbCY',
    appId: '1:159145555084:ios:352123daf901ca4d76f7a9',
    messagingSenderId: '159145555084',
    projectId: 'noteapp-38cb3',
    storageBucket: 'noteapp-38cb3.appspot.com',
    iosClientId: '159145555084-s3cqv0lvla281sh2mjoqohrov9gel1b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-I7BI1sThCGlofSSrmMlidyah8PVbCY',
    appId: '1:159145555084:ios:352123daf901ca4d76f7a9',
    messagingSenderId: '159145555084',
    projectId: 'noteapp-38cb3',
    storageBucket: 'noteapp-38cb3.appspot.com',
    iosClientId: '159145555084-s3cqv0lvla281sh2mjoqohrov9gel1b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
